[build]
target = "x86_64-blog_os.json"

# Allows us to use the bootimage runner to automatically
# link the compiled executable with the bootloader dep-
# endency and then launch QEMU (https://www.qemu.org/).
[target.'cfg(target_os = "none")']
runner = "bootimage runner"

[unstable]
# Enables `compiler_builtins`' implementations of needed
# memory functions (`memcpy`, `memset`, `memcmp`, &c).
build-std-features = ["compiler-builtins-mem"]

# Tells Cargo to recompile the `core` and `compiler_builtins` libraries
# instead of using the precompiled versions that ship with Rust.
build-std = ["core", "compiler_builtins"]
